// flow-typed signature: cf6c46395c4d5801c83ac7830a05ee21
// flow-typed version: <<STUB>>/angled-edges_v^2.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'angled-edges'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'angled-edges' {
  declare module.exports: any;
}
