// flow-typed signature: f661192cea7a7dc7dacf12fc27f15883
// flow-typed version: <<STUB>>/sass-burger_v^1.3.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-burger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-burger' {
  declare module.exports: any;
}
