// flow-typed signature: 57ab333ffee30d2c27d07eb3e7d19ca5
// flow-typed version: <<STUB>>/spinthatshit_v^1.0.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spinthatshit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spinthatshit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spinthatshit/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spinthatshit/gulpfile.js' {
  declare module.exports: $Exports<'spinthatshit/gulpfile'>;
}
