// flow-typed signature: 97aea1c0619ea2bbf3c358364eb826c8
// flow-typed version: <<STUB>>/travis-github-status_v^1.4.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-github-status'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-github-status' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'travis-github-status/dist/index' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/statuses/codeClimate' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/statuses/eslint' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/statuses/flow' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/statuses/index' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/statuses/jest' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/statuses/snyk' {
  declare module.exports: any;
}

declare module 'travis-github-status/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'travis-github-status/dist/index.js' {
  declare module.exports: $Exports<'travis-github-status/dist/index'>;
}
declare module 'travis-github-status/dist/statuses/codeClimate.js' {
  declare module.exports: $Exports<'travis-github-status/dist/statuses/codeClimate'>;
}
declare module 'travis-github-status/dist/statuses/eslint.js' {
  declare module.exports: $Exports<'travis-github-status/dist/statuses/eslint'>;
}
declare module 'travis-github-status/dist/statuses/flow.js' {
  declare module.exports: $Exports<'travis-github-status/dist/statuses/flow'>;
}
declare module 'travis-github-status/dist/statuses/index.js' {
  declare module.exports: $Exports<'travis-github-status/dist/statuses/index'>;
}
declare module 'travis-github-status/dist/statuses/jest.js' {
  declare module.exports: $Exports<'travis-github-status/dist/statuses/jest'>;
}
declare module 'travis-github-status/dist/statuses/snyk.js' {
  declare module.exports: $Exports<'travis-github-status/dist/statuses/snyk'>;
}
declare module 'travis-github-status/dist/utils.js' {
  declare module.exports: $Exports<'travis-github-status/dist/utils'>;
}
